//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Common.Persistence.Scripts.Employees {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostgresEmployeeElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostgresEmployeeElement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Common.Persistence.Scripts.Employees.PostgresEmployeeElement", typeof(PostgresEmployeeElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO EMPLOYEES(name, surname, phone, company_id, department_id) VALUES(@name, @surname, @phone, @companyId, @departmentId) RETURNING id as &quot;Id&quot;.
        /// </summary>
        internal static string CreateEmployee {
            get {
                return ResourceManager.GetString("CreateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM EMPLOYEES WHERE id = @id.
        /// </summary>
        internal static string DeleteEmployeeById {
            get {
                return ResourceManager.GetString("DeleteEmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  e.id AS Id,
        ///        e.name AS Name,
        ///        e.surname AS Surname,
        ///        e.phone AS Phone,
        ///        e.company_id AS CompanyId,
        ///        p.type AS PassportType,
        ///        p.number AS PassportNumber,
        ///        d.name AS DepartmentName,
        ///        d.phone AS DepartmentPhone
        ///FROM employees e
        ///         LEFT JOIN passports p ON p.employee_id = e.id
        ///         LEFT JOIN departments d ON e.department_id = d.id WHERE company_id = @companyId.
        /// </summary>
        internal static string GetCompanyEmployees {
            get {
                return ResourceManager.GetString("GetCompanyEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  e.id AS Id,
        ///        e.name AS Name,
        ///        e.surname AS Surname,
        ///        e.phone AS Phone,
        ///        e.company_id AS CompanyId,
        ///        p.type AS PassportType,
        ///        p.number AS PassportNumber,
        ///        d.name AS DepartmentName,
        ///        d.phone AS DepartmentPhone
        ///FROM employees e
        ///         LEFT JOIN passports p ON p.employee_id = e.id
        ///         LEFT JOIN departments d ON e.department_id = d.id WHERE department_id = @departmentId.
        /// </summary>
        internal static string GetDepartmentEmployees {
            get {
                return ResourceManager.GetString("GetDepartmentEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id as &quot;Id&quot;, name as &quot;Name&quot;, surname as &quot;Surname&quot;, phone as &quot;Phone&quot;, company_id as &quot;CompanyId&quot;, department_id as &quot;DepartmentId&quot; FROM employees where id=@id.
        /// </summary>
        internal static string GetEmployeeById {
            get {
                return ResourceManager.GetString("GetEmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id as &quot;Id&quot;, name as &quot;Name&quot;, surname as &quot;Surname&quot;, phone as &quot;Phone&quot;, company_id as &quot;CompanyId&quot; FROM employees where phone=@phone.
        /// </summary>
        internal static string GetEmployeeByPhone {
            get {
                return ResourceManager.GetString("GetEmployeeByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE employees
        ///SET name = @name,
        ///    surname = @surname,
        ///    phone = @phone,
        ///    company_id = @companyId,
        ///    department_id = @departmentId
        ///WHERE id = @employeeId
        ///    RETURNING id AS &quot;Id&quot;, 
        ///          name AS &quot;Name&quot;, 
        ///          surname AS &quot;Surname&quot;, 
        ///          phone AS &quot;Phone&quot;, 
        ///          company_id AS &quot;CompanyId&quot;, 
        ///          department_id AS &quot;DepartmentId&quot;;.
        /// </summary>
        internal static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
    }
}
