version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

    ports:
      - '5432:5432'

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
  
  api:
    build:
      context: ./
      dockerfile: ./Api/Dockerfile
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
    driver: bridge


volumes:
  pgdata: